### ISSUE TITLE
Exception: An item needs to be selected. Select and try again.

### ISSUE THREAD

**Issue by nix0x00** [magevision/magento2-mass-email-customers#1]
Hey, I was trying to customize the extension by adding it to Newsletter Subscribers, and when I select/check the email/subscribers and send email, I get Localized exception that "An item needs to be selected". I think I have added all the necessary requirements, the code I am using is given below:

https://github.com/nix0x00/newsletter_subscribers/blob/master/massSend.php

Could you please guide me here?

**Comment by magevision** [comment]
Old request, not related with the extension itself.
