### ISSUE TITLE
Redirecting to home page

### ISSUE THREAD

**Issue by ssniranga** [magevision/magento2-mass-email-customers#2]
Once the action complete. it's redirecting to home page rather than staying on the same page.

**Comment by magevision** [comment]
In which magento version?

**Comment by ssniranga** [comment]
2.4.5

**Comment by magevision** [comment]
Unfortunately is not reproducible. After the action is completed there is a redirect to the refererUrl. You need to debug in the controller and see the value of the $this->_redirect->getRefererUrl() ($_SERVER['HTTP_REFERER'])
